name: Build
run-name: Build
on: [workflow_dispatch]

jobs:
  build-apk:
    name: Build Android APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.1"
          channel: "stable"
      # - run: echo "${{ secrets.KEY_PROPERTIES_BASE64 }}" | base64 --decode > android/key.properties
      # - run: cat android/key.properties
      # - run: echo "${{ secrets.KEYSTORE1 }}" | base64 --decode > android/app/upload-keystore.jks
      - run: flutter --version
      - run: flutter pub get
      - run: flutter build apk --split-per-abi
      - uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: "build/app/outputs/flutter-apk"

  # build-appbundle:
  #   name: Build Android AppBundle
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-java@v3
  #       with:
  #         distribution: "zulu"
  #         java-version: "17"
  #     - uses: subosito/flutter-action@v2
  #       with:
  #         flutter-version: "3.10.0"
  #         channel: "stable"
  #     - run: echo "${{ secrets.KEY_PROPERTIES_BASE64 }}" | base64 --decode > android/key.properties
  #     - run: echo "${{ secrets.KEYSTORE1 }}" | base64 --decode > android/app/upload-keystore.jks
  #     - run: echo "${{ secrets.KEYSTORE1_PASS }}" > android/keystorepassword
  #     - run: flutter --version
  #     - run: flutter pub get
  #     - run: flutter build appbundle
  #     - run: bash sign-cafebazaar.sh
  #     - uses: actions/upload-artifact@v3
  #       with:
  #         name: android-app-bundle
  #         path: "build/app/outputs/bundle/release"

  publish-artifacts:
    name: Publish apk and appbundle files
    runs-on: ubuntu-latest
    needs: [build-apk]
    # needs: [build-apk, build-appbundle]
    steps:
      # - uses: actions/download-artifact@v3
      #   with:
      #     name: android-app-bundle
      - uses: actions/download-artifact@v3
        with:
          name: android-apk

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "*.apk,app-release.aab"
          tag: "alpha"
      # - uses: ncipollo/release-action@v1
      #   with:
      #     artifacts: "app-release.bin"
      #     token: ${{ secrets.MEDI_DEPLOY_ARTIFACTS }}
      #     owner: medicalstus
      #     repo: mobile-application-student